class HadethModel {
  String title;

  String content;

  final List<String> hadethTitlesEnglish = [
    "Hadeth 1",
    "Hadeth 2",
    "Hadeth 3",
    "Hadeth 4",
    "Hadeth 5",
    "Hadeth 6",
    "Hadeth 7",
    "Hadeth 8",
    "Hadeth 9",
    "Hadeth 10",
    "Hadeth 11",
    "Hadeth 12",
    "Hadeth 13",
    "Hadeth 14",
    "Hadeth 15",
    "Hadeth 16",
    "Hadeth 17",
    "Hadeth 18",
    "Hadeth 19",
    "Hadeth 20",
    "Hadeth 21",
    "Hadeth 22",
    "Hadeth 23",
    "Hadeth 24",
    "Hadeth 25",
    "Hadeth 26",
    "Hadeth 27",
    "Hadeth 28",
    "Hadeth 29",
    "Hadeth 30",
    "Hadeth 31",
    "Hadeth 32",
    "Hadeth 33",
    "Hadeth 34",
    "Hadeth 35",
    "Hadeth 36",
    "Hadeth 37",
    "Hadeth 38",
    "Hadeth 39",
    "Hadeth 40",
    "Hadeth 41",
    "Hadeth 42",
    "Hadeth 43",
    "Hadeth 44",
    "Hadeth 45",
    "Hadeth 46",
    "Hadeth 47",
    "Hadeth 48",
    "Hadeth 49",
    "Hadeth 50",
  ];

  HadethModel({required this.title, required this.content});
}
